// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgRGW3lIPrncnh64CBdk3HcD_oM5hVvcA',
    appId: '1:116100268011:web:7d212f9a20c113fea623ae',
    messagingSenderId: '116100268011',
    projectId: 'avocat-ad93d',
    authDomain: 'avocat-ad93d.firebaseapp.com',
    storageBucket: 'avocat-ad93d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBm9LN7d4TThw_ED_nmN_9iCHJyz7OB2J4',
    appId: '1:116100268011:android:a0355b4d36d042dda623ae',
    messagingSenderId: '116100268011',
    projectId: 'avocat-ad93d',
    storageBucket: 'avocat-ad93d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8cBA88L1_CQ5T-_kcRTxNjfsmEWnUWjc',
    appId: '1:116100268011:ios:f2246a491757ca66a623ae',
    messagingSenderId: '116100268011',
    projectId: 'avocat-ad93d',
    storageBucket: 'avocat-ad93d.appspot.com',
    iosClientId: '116100268011-mf4ld72ecndr74ki6l68s751db7jkkv0.apps.googleusercontent.com',
    iosBundleId: 'com.example.avocat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8cBA88L1_CQ5T-_kcRTxNjfsmEWnUWjc',
    appId: '1:116100268011:ios:cd453f211205861ba623ae',
    messagingSenderId: '116100268011',
    projectId: 'avocat-ad93d',
    storageBucket: 'avocat-ad93d.appspot.com',
    iosClientId: '116100268011-thcm931kp3t945413ejqiam5i0579tqs.apps.googleusercontent.com',
    iosBundleId: 'com.example.avocat.RunnerTests',
  );
}
